#lagoon-core
imageTag: v2.3.0
# api:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/api
#     tag: latest

# apiDB:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/api-db
#     tag: latest

# broker:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/broker
#     tag: latest

# ssh:
#   replicaCount: 1
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/ssh
#     tag: latest

# webhookHandler:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/webhook-handler
#     tag: latest

# webhooks2tasks:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/webhooks2tasks
#     tag: latest


# lagoon-build-deploy
overrideBuildDeployImage: registry.172.17.0.2.nip.io:32080/library/lagoon/kubectl-build-deploy-dind:latest

# This sets the same password in the lagoon-core-broker and lagoon-build-deploy to allow them to communicate
rabbitMQPassword: xogie5lae8IoshugahcoeThakiequo3I
# This sets the same authserver client secret in lagoon-core and lagoon-test
keycloakAuthServerClientSecret: 2da72b5c-f97f-4d6a-93cf-2a8996ee50d4
# DBaaS Passwords
auth:
  rootPassword: ba7ees3aiy0eiNai
postgresqlPassword: ba7ees3aiy0eiNai
#lagoon-remote
lagoon-build-deploy:
  enabled: false
dbaas-operator:
  mariadbProviders:
    development:
      password: ba7ees3aiy0eiNai
  postgresqlProviders:
    development:
      password: ba7ees3aiy0eiNai
  mongodbProviders:
    development:
      password: ba7ees3aiy0eiNai
# dockerHost:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/docker-host
#     tag: latest

# lagoon-test uses this
token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlQwWExwRklRd2M1TkVYWFVmZ2JMYjNwZ1ZXa2w3MEo1VDloZ1BpZUpTQVkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJsYWdvb24iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoibGFnb29uLWJ1aWxkLWRlcGxveS10b2tlbi04d2hiZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJsYWdvb24tYnVpbGQtZGVwbG95Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTBmYmY4YmQtNDFlNS00MmI3LWIzN2MtZDg5YjM4YWE1ZDMyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmxhZ29vbjpsYWdvb24tYnVpbGQtZGVwbG95In0.Y9zB4V0jW7trfUC_1mp9YbUFeOFUVOA7EQu5B2Z9TT8-gGFxr411l9Vwjp294YSOX35TFRaISdac3uRnf2Oe2smn6cpzC3rPzfnyexcTw5dFAW-VxY4uq40gSOC0E_KATWVdM7wZRustpXis0WDhH4fp5TayXFC9xP3TJH4ddqMq01_lHN-sJbrVsxW3mAw3f1xCBxha1lkArXDL-o7b_SjaZ4DD6WngR9l_AtjxdhpltE1h-Fa_saEMaeigpnTWZSrTK2acI9JNbz3t2urMJ7BHhwMx0tcSJH-3qru-DV7__qaSsLwnTVtsi57k0aCBhbnWcyUTCLo6IkOERn_jEg
# localGit:
#   image:
#     repository: testlagoon/local-git
#     tag: main

# localAPIDataWatcherPusher:
#   image:
#     repository: registry.172.17.0.2.nip.io:32080/library/lagoon/local-api-data-watcher-pusher
#     tag: latest

tests:
  # image:
  #   repository: registry.172.17.0.2.nip.io:32080/library/lagoon/tests
  #   tag: latest
  tests:
    # - active-standby-kubernetes
    # - api
    # - bitbucket
    # - dbaas
    # - deploytarget
    # - drupal-php74
    # - drupal-php80
    # - drupal-postgres
    # - drush
    # - elasticsearch
    # - features-api-variables
    # - features-kubernetes-2
    # - features-kubernetes
    # - generic
    # - github
    # - gitlab
    # - image-cache
    - nginx
    # - node-mongodb
    # - node-various
    # - node
    # - python
    # - tasks
