name: Lagoon test

on:
  push:
    branches:
      - helm_actions
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.21.1]
        experimental: [false]
        # include:
        #   - kindest_node_version: v1.22.0
        #     experimental: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    # - name: Setup correct Go version
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: '1.16'
    # - name: Run Kubernetes tools
    #   uses: stefanprodan/kube-tools@v1
    - name: Get Kind IP
      run: |
        docker network create kind || true && docker run --rm --network kind alpine ip -o addr show eth0 | sed -nE 's/.* ([0-9.]{7,})\/.*/\1/p'
        echo "kind_ip=$(docker network create kind || true && docker run --rm --network kind alpine ip -o addr show eth0 | sed -nE 's/.* ([0-9.]{7,})\/.*/\1/p')" >> $GITHUB_ENV
        echo "Kind cluster is at ${{ env.kind_ip }}"
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "192.168.224.2"
        replace: ${{ env.kind_ip }}
        include: "helmvalues/*.yaml"
    - name: Check config
      run: |
        cat helmvalues/kind-config.yaml
    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        config: helmvalues/kind-config.yaml
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        wait: 120s
    - name: Test
      run: |
        kubectl cluster-info
        kubectl get pods -A
    - name: Configure Helm repositories
      run: |
        helm plugin install https://github.com/aslafy-z/helm-git
        helm repo add harbor https://helm.goharbor.io
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo add stable https://charts.helm.sh/stable
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add minio https://helm.min.io/
        helm repo add amazeeio https://amazeeio.github.io/charts/
        helm repo add lagoon https://uselagoon.github.io/lagoon-charts/
        helm repo update