name: Lagoon test

on:
  push:
    branches:
      - helm_actions
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.21.1]
        experimental: [false]
        # include:
        #   - kindest_node_version: v1.22.0
        #     experimental: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    # - name: Setup correct Go version
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: '1.16'
    # - name: Run Kubernetes tools
    #   uses: stefanprodan/kube-tools@v1
    - name: Get Kind IP
      run: |
        docker network create kind || true && docker run --rm --network kind alpine ip -o addr show eth0 | sed -nE 's/.* ([0-9.]{7,})\/.*/\1/p'
        echo "kind_ip=$(docker network create kind || true && docker run --rm --network kind alpine ip -o addr show eth0 | sed -nE 's/.* ([0-9.]{7,})\/.*/\1/p')" >> $GITHUB_ENV
    - name: Show Kind IP
      run: |
        echo "${{ env.kind_ip }}"
    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        # config: test-resources/kind-config.yaml
    - name: Test
      run: |
        kubectl cluster-info
        kubectl get pods -A
